language: php

php:
  - 5.4

env:
  - PROJECT_NAME=myplanet DRUSH_VERSION=5.7

before_install: bash tmp/scripts/travis_before_install.sh

before_script: bash tmp/scripts/travis_install.sh

script: bash tmp/scripts/travis_test.sh
