language: php

php:
  - 5.4

env:
  - PROJECTNAME=myplanet DRUSH_VERS=5.7

before_install: bash tmp/scripts/travis_before_install.sh

before_script: bash tmp/scripts/travis_install.sh

script: bash tmp/scripts/travis_test.sh
