<?php

function myplanetdigital_init() {
	if (arg(0) == 'admin' && arg(1) == 'structure' && arg(2) == 'pages') {
		$bue_id = 1;
	    bueditor_settle($bue_id);
	    $bue_setting['BUE']['preset']['edit-body'] = "e$bue_id";
	    drupal_add_js($bue_setting, 'setting');
	    drupal_add_css('.bue-popup{z-index: 1001 !important}', array('type' => 'inline'));
	}
}

function myplanetdigital_custom_theme() {
	$path_alias = drupal_get_path_alias();
	$url = explode('/', $path_alias);
	
	if ($url[0] == 'fellowships') {
		return 'fellowships';
	}
}

function myplanetdigital_form_alter(&$form, &$form_state, $form_id) {
	switch ($form_id) {
		case 'commerce_checkout_form_checkout' :
			$form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['name_block']['name_line']['#title'] = 'Name';
			break;
	}
}

function invoice_payment_form_output() {
	return '';
	global $user;

	$order = commerce_cart_order_load($user->uid);

	if ($order === false) {
		$order = commerce_cart_order_new($user->uid);
		$order = commerce_cart_order_load($user->uid);
	}

	if (count($order->commerce_line_items) == 0) {
		commerce_cart_product_add_by_id(1);
		unset($_SESSION['messages']['status']);
	}
	
	require_once(drupal_get_path('module', 'commerce_checkout') . '/includes/commerce_checkout.pages.inc');	
	$output = drupal_render(commerce_checkout_router($order));
	
	return $output;
}
