<?php

function panels_css_js_files_page_manager_variant_operations_alter(&$operations, $handler) {
	reset($operations['children']);
	$children_operations = array();
	while (list($key, $value) = each($operations['children'])) {
		$children_operations[$key] = $value;
		if ($key == 'context') {
			$children_operations['css_js_files'] = array(
				'title' => t('CSS & JS Files'),
				'description' => t('Add additional CSS & JS files.'),
				'form' => 'panels_css_js_files_variant_form',
			);
		}
	}
	$operations['children'] = $children_operations;
}

function panels_css_js_files_variant_form($form, &$form_state) {
	$handler = &$form_state['handler'];
	
	if (empty($handler->conf['panels_css_js_files_css'])) {
		$handler->conf['panels_css_js_files_css'] = '';
	}
	
	if (empty($handler->conf['panels_css_js_files_js'])) {
		$handler->conf['panels_css_js_files_js'] = '';
	}
	
	$form['settings']['panels_css_js_files_css'] = array(
		'#type' => 'textarea',
		'#title' => t('CSS Files'),
		'#description' => t('Enter one file per line.'),
		'#default_value' => $handler->conf['panels_css_js_files_css'],
	);
	
	$form['settings']['panels_css_js_files_js'] = array(
		'#type' => 'textarea',
		'#title' => t('JS Files'),
		'#description' => t('Enter one file per line.'),
		'#default_value' => $handler->conf['panels_css_js_files_js'],
	);
	
	return $form;
}

function panels_css_js_files_variant_form_submit($form, &$form_state) {
	$form_state['handler']->conf['panels_css_js_files_css'] = $form_state['values']['panels_css_js_files_css'];
	$form_state['handler']->conf['panels_css_js_files_js'] = $form_state['values']['panels_css_js_files_js'];
}

function panels_css_js_files_ctools_render_alter($info, $page, $context) {
	$conf = $context['handler']->conf;
	
	if (!isset($conf['panels_css_js_files_css'])) return;
	
	$css = $conf['panels_css_js_files_css'];
	$js = $conf['panels_css_js_files_js'];
	
	global $theme_info;
	$theme_path = dirname($theme_info->filename);
	
	if ($css) {
		foreach (array_filter(array_map('trim', explode(PHP_EOL, $css)), 'strlen') as $css_file) {
			$path = mb_strpos($css_file, '://') === false ? $theme_path . '/css/' . $css_file : $css_file;
			drupal_add_css($path);
		}
	}
	
	if ($js) {
		foreach (array_filter(array_map('trim', explode(PHP_EOL, $js)), 'strlen') as $js_file) {
			$path = mb_strpos($js_file, '://') === false ? $theme_path . '/js/' . $js_file : $js_file;
			drupal_add_js($path);
		}
	}	
}
